
on: push
name: on push
jobs:
  gitHubActionForPytest:
    name: GitHub Action for pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@master
      with:
        args: python setup.py develop
    - name: Run unit tests
      with:
        args: pytest
        env: ./TimeLeap/time_leap/colorization/Tests
